### ISSUE TITLE
左右滑动,居中选中有偏差了

### ISSUE THREAD

**Issue by huyanghu** [SilenceBurst/WheelChart#2]

**Comment by yongshengdev** [comment]
麻烦提供下复现步骤

**Comment by huyanghu** [comment]
你在WheelChartLayout类中加个居中指示
    @Override
    protected void dispatchDraw(Canvas canvas) {
        super.dispatchDraw(canvas);
        canvas.drawLine(getWidth() / 2, 0, getWidth() / 2, getHeight(),mPaint);
    }

左右多次滑动,就回看到不居中情况了,是必须的

**Comment by yongshengdev** [comment]
指示器要跟随滚动的，在WheelChartLayout中绘制就没有这样效果了 麻烦可不可以加下我qq 3328019207，录屏给我看下，我这边左右滑动没有复现过

**Comment by yongshengdev** [comment]
OverScroller最后一次的滚动判断有误，已解决。
